# Use postgres/example user/password credentials
version: '3.1'

services:
  server:
    build: .
    depends_on:
      - db
    ports:
    - 3000:3000
    volumes:
    - .:/opt/app
    - /opt/app/node_modules
  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: user
      POSTGRES_DB: database

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080